import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { cn } from "@/lib/utils";
import Backgroud from "@/components/backgroud";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW">
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          "antialiased",
          "relative min-h-screen min-w-screen bg-gradient-to-br from-[#06000F] via-[#06000fd6] to-[#06000F]"
        )}
      >
        <Backgroud />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
